### ISSUE TITLE
Can this be used to create mzTab files from common inputs?

### ISSUE THREAD

**Issue by sorenwacker** [lifs-tools/pymzTab-m#11]
Hi,

I didn't find any information in the repo readme whether or not this library can create mzTab files.

Is there a tutorial available e.g. how to create an mztab file from MaxQuant data or metabolomics data? 

Or can you point me to any such resource?

**Comment by nilshoffmann** [comment]
Hi! This library is geared towards handling mzTab-M (for metabolomics), so using it for MaxQuant data is not intended, unless MaxQuant is also now available for Metabolomics. Concerning Metabolomics / lipidomics data, please take a look at the following test, which creates an mzTab-M object tree, which is then serialized to JSON and sent to the validation endpoint:
https://github.com/lifs-tools/pymzTab-m/blob/master/tests/mztab_m_swagger_client/test_validate_api.py

This library was generated using the swagger-codegen project based on the the object and api description served here: https://apps.lifs-tools.org/mztabvalidator/v2/api-docs
This also serves the validation endpoint where you can send an mzTab-m to: https://apps.lifs-tools.org/mztabvalidator/swagger-ui.html

You can also use this library to create a JSON of the mzTab-m and use our Java implementation  (also available as a bioconda tool and container) to convert the JSON to the tab separated format: https://github.com/lifs-tools/jmzTab-m

**Comment by sorenwacker** [comment]
Thanks for the clarification. The code that you shared, seems to be only testing code. I wonder how to create a mztab file from common outputs. Is everyone in the community creating its own parsers? Seems the public sources ones are only validators of the format. Are you aware of a tutorial, how to create an mztab file from a certain output?

**Comment by nilshoffmann** [comment]
To my knowledge, LDA2 uses the Java library to create mzTab-M. Most tools create the format by themselves and then use the validator to check their implementation or simply parse it with a CSV/TSV parser and pick out the information they are interested in.

For some examples, see: 
https://github.com/HUPO-PSI/mzTab/tree/master/examples/2_0-Metabolomics_Release

The specification document:
https://hupo-psi.github.io/mzTab/2_0-metabolomics-release/mzTab_format_specification_2_0-M_release.html

Concerning "common" outputs, what would those be in your case? I am happy to offer you some guidance, maybe collecting our notes as a tutorial to also help others getting started.

**Comment by nilshoffmann** [comment]
@jacobomiranda knows more about using Python to write mzTab-M for LipidXplorer.

**Comment by sorenwacker** [comment]
Interesting, there seem to be no free implementation of a parser around. Thanks.
